#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-persistent
Version  : 4.8.0
Release  : 61
URL      : https://files.pythonhosted.org/packages/9c/cc/4d3da408fc1e37cb6481c9ea345159608fa4f0263efc6734c0314d571c0a/persistent-4.8.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/9c/cc/4d3da408fc1e37cb6481c9ea345159608fa4f0263efc6734c0314d571c0a/persistent-4.8.0.tar.gz
Summary  : Translucent persistent objects
Group    : Development/Tools
License  : ZPL-2.1
Requires: pypi-persistent-license = %{version}-%{release}
Requires: pypi-persistent-python = %{version}-%{release}
Requires: pypi-persistent-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(cffi)
BuildRequires : pypi(py)
BuildRequires : pypi(zope.interface)
BuildRequires : pypi-pluggy
BuildRequires : pypi-pytest
BuildRequires : pypi-tox
BuildRequires : pypi-virtualenv
BuildRequires : python3-dev

%description
===========================================================
``persistent``:  automatic persistence for Python objects
===========================================================

%package dev
Summary: dev components for the pypi-persistent package.
Group: Development
Provides: pypi-persistent-devel = %{version}-%{release}
Requires: pypi-persistent = %{version}-%{release}

%description dev
dev components for the pypi-persistent package.


%package license
Summary: license components for the pypi-persistent package.
Group: Default

%description license
license components for the pypi-persistent package.


%package python
Summary: python components for the pypi-persistent package.
Group: Default
Requires: pypi-persistent-python3 = %{version}-%{release}

%description python
python components for the pypi-persistent package.


%package python3
Summary: python3 components for the pypi-persistent package.
Group: Default
Requires: python3-core
Provides: pypi(persistent)
Requires: pypi(cffi)
Requires: pypi(zope.interface)

%description python3
python3 components for the pypi-persistent package.


%prep
%setup -q -n persistent-4.8.0
cd %{_builddir}/persistent-4.8.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1646664358
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-persistent
cp %{_builddir}/persistent-4.8.0/LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-persistent/a0b53f43aab58b46bf79ba756c50771c605ab4c5
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/python3.10/persistent/cPersistence.h
/usr/include/python3.10/persistent/ring.h

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-persistent/a0b53f43aab58b46bf79ba756c50771c605ab4c5

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
